import { v } from "convex/values";
import { action, internalMutation, internalQuery } from "./_generated/server";
import type { MutationCtx } from "./_generated/server";
import { internal } from "./_generated/api";
import { createAccount } from "@convex-dev/auth/server";
import { Scrypt } from "lucia";

/**
 * Admin seeding — exactly TWO admin accounts, created from the Keys tab
 * environment variables. Credentials are NEVER hard-coded here and NEVER
 * returned to any caller.
 *
 * Configure in the project's Keys / API keys tab:
 *   ADMIN_1_EMAIL, ADMIN_1_PASSWORD   (or ADMIN_1_PASSWORD_HASH — Lucia
 *   scrypt format "scrypt$salt$hash", e.g. generated by Lucia's Scrypt)
 *   ADMIN_2_EMAIL, ADMIN_2_PASSWORD   (or ADMIN_2_PASSWORD_HASH)
 *
 * Run once after configuring: `bunx convex run adminSetup:seedAdmins`
 * (or `bunx convex run adminSetup:seedAdmins --prod` for production).
 * The action reports only status ("created" / "exists" / "skipped"), never
 * secrets. Safe to re-run; idempotent.
 */

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

function readAdminConfig(index: 1 | 2) {
  const email = (process.env[`ADMIN_${index}_EMAIL`] ?? "").trim().toLowerCase();
  const password = process.env[`ADMIN_${index}_PASSWORD`];
  const passwordHash = process.env[`ADMIN_${index}_PASSWORD_HASH`];
  return { email, password, passwordHash };
}

function validateConfig(index: 1 | 2) {
  const cfg = readAdminConfig(index);
  if (!cfg.email) {
    return { error: `ADMIN_${index}_EMAIL is not set in the environment.` as const };
  }
  if (!EMAIL_RE.test(cfg.email)) {
    return { error: `ADMIN_${index}_EMAIL is not a valid email address.` as const };
  }
  if (!cfg.password && !cfg.passwordHash) {
    return {
      error: `ADMIN_${index}_PASSWORD (or ADMIN_${index}_PASSWORD_HASH) is not set.` as const,
    };
  }
  if (cfg.password && cfg.password.length < 8) {
    return { error: `ADMIN_${index}_PASSWORD must be at least 8 characters.` as const };
  }
  return { cfg };
}

/** Create-or-promote the user row for an admin email. */
async function ensureAdminUser(ctx: MutationCtx, email: string) {
  const existing = await ctx.db
    .query("users")
    .withIndex("email", (q) => q.eq("email", email))
    .unique();
  if (existing) {
    if (existing.role !== "admin") await ctx.db.patch(existing._id, { role: "admin" });
    return { userId: existing._id, status: "exists" as const };
  }
  const userId = await ctx.db.insert("users", {
    email,
    name: email.split("@")[0],
    role: "admin",
  });
  return { userId, status: "created" as const };
}

/**
 * Plaintext path: createAccount hashes the password with the Password
 * provider's own Scrypt, so the credentials sign in through the standard
 * password flow.
 */
export const upsertAdminInternal = internalMutation({
  args: { email: v.string(), password: v.string() },
  handler: async (ctx, args) => {
    const email = args.email.trim().toLowerCase();
    const existing = await ctx.db
      .query("users")
      .withIndex("email", (q) => q.eq("email", email))
      .unique();
    if (existing) {
      if (existing.role !== "admin") await ctx.db.patch(existing._id, { role: "admin" });
      return { status: "exists" as const };
    }
    // createAccount only performs ctx.runMutation("auth:store", …), which is
    // valid from within a mutation — the wider ActionCtx type is satisfied by cast.
    const { user } = await createAccount(
      ctx as unknown as Parameters<typeof createAccount>[0],
      {
        provider: "password",
        account: { id: email, secret: args.password },
        profile: { email, name: email.split("@")[0] },
      },
    );
    await ctx.db.patch(user._id, { role: "admin" });
    return { status: "created" as const };
  },
});

/**
 * Pre-hashed path (ADMIN_n_PASSWORD_HASH, Lucia scrypt "scrypt$salt$hash"):
 * createAccount would re-hash the string, so the account row is written
 * directly with the exact schema fields of authAccounts.
 */
export const upsertAdminPrehashedInternal = internalMutation({
  args: { email: v.string(), passwordHash: v.string() },
  handler: async (ctx, args) => {
    const email = args.email.trim().toLowerCase();
    const { userId, status } = await ensureAdminUser(ctx, email);
    const account = await ctx.db
      .query("authAccounts")
      .withIndex("providerAndAccountId", (q) =>
        q.eq("provider", "password").eq("providerAccountId", email),
      )
      .unique();
    if (!account) {
      await ctx.db.insert("authAccounts", {
        userId,
        provider: "password",
        providerAccountId: email,
        secret: args.passwordHash,
      });
      return { status: status === "created" ? ("created" as const) : ("updated" as const) };
    }
    return { status: "exists" as const };
  },
});

/**
 * Seed the two admin accounts from the environment. Requires both configs
 * to validate before any write. Reports per-admin status only.
 */
export const seedAdmins = action({
  args: {},
  handler: async (ctx) => {
    const results: Array<{ admin: string; status: string; note?: string }> = [];

    for (const index of [1, 2] as const) {
      const check = validateConfig(index);
      if ("error" in check) {
        results.push({ admin: `ADMIN_${index}`, status: "skipped", note: check.error });
        continue;
      }
      const { cfg } = check;

      if (cfg.passwordHash) {
        const result = await ctx.runMutation(internal.adminSetup.upsertAdminPrehashedInternal, {
          email: cfg.email,
          passwordHash: cfg.passwordHash,
        });
        results.push({ admin: `ADMIN_${index}`, status: result.status });
      } else {
        const result = await ctx.runMutation(internal.adminSetup.upsertAdminInternal, {
          email: cfg.email,
          password: cfg.password as string,
        });
        results.push({ admin: `ADMIN_${index}`, status: result.status });
      }
    }

    return {
      seeded: results,
      hint: "Status 'skipped' means the matching ADMIN_n_* keys are not configured yet.",
    };
  },
});

/** Sanity action for the test harness: is a given email an admin? */
export const isAdminEmail = action({
  args: { email: v.string() },
  handler: async (ctx, args): Promise<{ exists: boolean; isAdmin: boolean }> => {
    return await ctx.runQuery(internal.adminSetup.adminStatusQuery, {
      email: args.email.trim().toLowerCase(),
    });
  },
});

export const adminStatusQuery = internalQuery({
  args: { email: v.string() },
  handler: async (ctx, args) => {
    const user = await ctx.db
      .query("users")
      .withIndex("email", (q) => q.eq("email", args.email))
      .unique();
    return { exists: !!user, isAdmin: user?.role === "admin" };
  },
});
